### ISSUE TITLE
How to roll back to normal

### ISSUE THREAD

**Issue by athulmekkoth** [PEAKYCOMMAND/Zorin-OS-Pro#3]
I have updated to the pro version and when I try to update now they are asking for the serial number before starting the update.

**Comment by Hyphonic** [comment]
I think you just have to remove `https://packages.zorinos.com/premium focal main` from the source list and delete `99zorin-os-premium-user-agent` from _/etc/apt/apt.conf.d/_

**Comment by athulmekkoth** [comment]
Thanks, i will cry it
